DECLARE 
	@CONTADOR INT = 105,
	@DATA DATETIME = '20200702'
BEGIN
	WHILE @CONTADOR < 123
		BEGIN
			IF (@CONTADOR < 115 OR @CONTADOR >119) AND (@CONTADOR != 122 AND @CONTADOR != 123)
				PRINT 'DATA: '+CONVERT(VARCHAR,@DATA,@CONTADOR)
			SET @CONTADOR = @CONTADOR + 1
		END
END
GO