
-- Estrutura
CREATE TABLE TABELA (CODIGO INTEGER, VALOR VARCHAR2(40) NOT NULL);
ALTER TABLE TABELA ADD CONSTRAINT CODIGO_PK PRIMARY KEY (CODIGO);
CREATE SEQUENCE CONTADOR;

-- trigger

-- trigger de inicio
CREATE OR REPLACE TRIGGER GATILHO_BEFORE
    BEFORE INSERT OR UPDATE OR DELETE
    OF CODIGO, VALOR
    ON TABELA
    FOR EACH ROW
    WHEN(NEW.CODIGO < 1 OR NEW.VALOR IS NULL)
    BEGIN
        raise_application_error(-20001,'Valor invalido');
    END GATILHO_BEFORE;

-- TRIGGER FIM
    CREATE OR REPLACE TRIGGER GATILHO_AFTER
    AFTER INSERT OR UPDATE OR DELETE
        ON TABELA
    BEGIN    
        DBMS_OUTPUT.PUT_LINE('OPERACAO REALIZADO COM SUCESSO!');    
    END GATILHO_AFTER;  


-- inserindo valor
INSERT INTO TABELA VALUES(CONTADOR.NEXTVAL,'VALOR1');
INSERT INTO TABELA VALUES(CONTADOR.NEXTVAL,'VALOR2');

-- Valores que darao erro pela TRIGGER
INSERT INTO TABELA VALUES (-1,'A');
INSERT INTO TABELA VALUES (CONTADOR.NEXTVAL,'');

-- Apagando

DROP TABLE TABELA;
DROP SEQUENCE CONTADOR;
DROP TRIGGER GATILHO_AFTER;
DROP TRIGGER GATILHO_BEFORE;