-- CASE basico.
SELECT 
	CASE
		WHEN F.ID % 2 = 0 THEN 'PAR: ' + CAST(F.ID AS VARCHAR)
		ELSE 'IMPAR: ' + CAST(F.ID AS VARCHAR)
	END AS 'ID',
	F.NOME
FROM DBO.FUNCIONARIO_DADO AS F
GO

-- Dois CASES juntos
SELECT 
	CASE
		WHEN F.ID % 2 = 0 THEN 'PAR: ' + CAST(F.ID AS VARCHAR)
		ELSE 'IMPAR: ' + CAST(F.ID AS VARCHAR)
	END AS 'ID',
	CASE 
		WHEN F.NOME = F.NOME THEN 'Nome: ' + F.NOME
	END AS 'NAME'
FROM DBO.FUNCIONARIO_DADO AS F
GO