CREATE TABLE FUNCIONARIO_DADO (ID SMALLINT IDENTITY,NOME VARCHAR(50) NOT NULL)
CREATE TABLE FUNCIONARIO_END(ID SMALLINT IDENTITY, FK SMALLINT, RUA VARCHAR(50) NOT NULL, CIDADE VARCHAR(20) NOT NULL, ESTADO CHAR(2) NOT NULL)
ALTER TABLE FUNCIONARIO_DADO ADD CONSTRAINT FUNC_DADO_PK PRIMARY KEY(ID)
ALTER TABLE FUNCIONARIO_END ADD CONSTRAINT FUNC_END_PK PRIMARY KEY(ID)
ALTER TABLE FUNCIONARIO_END ADD CONSTRAINT FUNC_FK_DADO_END FOREIGN KEY (FK) REFERENCES FUNCIONARIO_DADO(ID)
GO

-- Procedimento sem parametros.
CREATE PROC SELECTIONAR_TUDO
AS
	SELECT D.ID, D.NOME,E.RUA,E.CIDADE,E.ESTADO	 
	FROM FUNCIONARIO_DADO D INNER JOIN FUNCIONARIO_END E
	ON D.ID = E.FK 
GO

-- CHAMANDO
EXEC SELECTIONAR_TUDO
GO

-- Procedimentos com parametros @ID
CREATE PROCEDURE SELECIONAR_ID @ID SMALLINT
AS
	SELECT D.ID, D.NOME,E.RUA,E.CIDADE,E.ESTADO	 
	FROM FUNCIONARIO_DADO D INNER JOIN FUNCIONARIO_END E
	ON D.ID = E.FK
	WHERE D.ID = @ID 
GO

-- Chamando
EXEC SELECIONAR_ID 1
GO

-- Procedimento para inserir em duas tabelas ao mesmo tempo.
CREATE PROC INSERIR @NOME VARCHAR(50), @RUA VARCHAR(50), @CIDADE VARCHAR(20), @ESTADO CHAR(2)
AS
	INSERT INTO FUNCIONARIO_DADO (NOME) VALUES (@NOME)
	-- @@IDENTITY PEGA O ULTIMO VALOR GERADO POR IDENTITY
	INSERT INTO FUNCIONARIO_END(FK,RUA,CIDADE,ESTADO) VALUES (@@IDENTITY,@RUA,@CIDADE,@ESTADO)
GO

-- Usando o procedimento INSERIR acima.
EXEC INSERIR 'JOAO','RUA DAS FLORES','RIO DE JANEIRO','RJ'
EXEC INSERIR 'MARIA','RUA DAS MARGARIDAS','SAO PAULO','SP'
EXEC INSERIR 'JOSE','RUA CINZA','CURITIBA','PR'
EXEC INSERIR 'MARCOS','RUA PORTO','PORTO ALEGRE','RS'
EXEC INSERIR 'ANA','RUA GIZ','BELO HORIZONTE','MG'
GO

-- Voce pode chamar sem o EXEC, mas nao eh recomendavel
SELECIONAR_ID 3
GO