-- Apagar procedure
DROP PROC RETORNA_NOME
GO

CREATE PROC RETORNA_NOME @ID SMALLINT, @NOME VARCHAR(50) OUTPUT
AS
	SELECT @NOME = NOME FROM DBO.FUNCIONARIO_DADO
	WHERE ID = @ID
GO

-- Criando variavel local
DECLARE @SAIDA varchar(50)
-- Usando o procedimento para atribuir valor a ela
EXEC RETORNA_NOME 2, @NOME = @SAIDA OUTPUT
-- projetando
SELECT @SAIDA as "OUTPUT"
GO

-- Criando variavel global
DECLARE @@VISIVEL VARCHAR(50)
EXEC RETORNA_NOME 3, @NOME = @@VISIVEL OUTPUT
SELECT @@VISIVEL AS "VALOR GLOBAL"
GO